# -*- coding: utf-8 -*-
"""ML-MusicData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUbYhLyukPMAqZEj5oEslZOXRVnr5VJe
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

"""Data are MC generated to simulate registration of high energy gamma particles in an atmospheric Cherenkov telescope
https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope
"""

# cols = ['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long','fM3Trans','fAlpha','fDist','class']
music_data = pd.read_csv('music.csv')
music_data.head()

music_data.shape

music_data.describe()

"""Train, Validation, Test Datasets"""

music_data.info()

music_data.values

X= music_data.drop(columns=['genre'])
y = music_data['genre']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

model = DecisionTreeClassifier()
model.fit(X_train,y_train)
music_data

predictions = model.predict(X_test)
score = accuracy_score(y_test, predictions)
score



